import type { Metadata } from "next";
import { Onest } from "next/font/google"
import "./globals.css";
import { ThemeClientProvider } from "@/ui/provider/Provider";

const onest = Onest({ weight: "400", subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeClientProvider>
        <body className={onest.className}>
          {children}
        </body>
      </ThemeClientProvider>
    </html>
  );
}
